title: Side Stories
email: info@sidestories.fi
description:
  fi: >
    Helsingissä toimiva lyhytelokuviin ja dokumentteihin erikoistunut tuotantoyhtiö
  en: > # this means to ignore newlines until "baseurl:"
    Helsinki based film production company focusing on shorts and docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sidestories.fi" # the base hostname & protocol for your site
twitter_username: sidestoriesfi

# Build settings
markdown: kramdown
theme: minima

# Polyglot config.
languages: ["fi", "en"]
default_lang: "fi"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
data_dir: ./_data

collections:
  projects:
    output: true
