title: Side Stories
email: info@sidestories.fi
description:
  fi: >
    Helsingissä toimiva lyhytelokuviin ja dokumentteihin erikoistunut tuotantoyhtiö
  en: > # this means to ignore newlines until "baseurl:"
    Helsinki based film production company focusing on shorts and docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sidestories.fi" # the base hostname & protocol for your site
twitter_username: sidestoriesfi

# Build settings
markdown: kramdown
theme: minima

gem:
- jekyll-autoprefixer

# Polyglot config.
languages: ["fi", "en"]
default_lang: "fi"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
data_dir: ./_data

collections:
  projects:
    output: true
  galleries:
    output: false

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 60
  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 1920
      quality: 40
    - width: 1440
      quality: 50
    - width: 1024
    - width: 800
    - width: 480
    - width: 280
    - width: 32
      quality: 20